### ISSUE TITLE
Set select option 'selected' by value

### ISSUE THREAD

**Issue by MsFoued** [techouse/select-auto-complete#5]
I have this code for populating a new select-auto-complete :

`SelectAutoComplete::make('Origin market', 'origin_market')->options(collect($mergedMarketsOptions)->mapWithKeys(function ($option) {
              return [$option['code'] => $option['name']];
            }))->displayUsingLabels()->hideFromIndex(),`

How can i set one of these options as selected by default?

**Comment by techouse** [comment]
Thanks for bringing this to my attention.

There is already an ugly [Laravel Nova way](https://github.com/laravel/nova-issues/issues/58#issuecomment-419754713) to do this using `->withMeta(["value" => "Some Value"])`. However since it's quite weird and undocumented 😅 I decided to add a few more options/features to this plugin.

As of [v1.1.0](https://github.com/techouse/select-auto-complete/releases/tag/v1.1.0) you can use the [`->default()`](https://github.com/techouse/select-auto-complete/blob/master/src/SelectAutoComplete.php#L45) option to do this. Just remember to set it equal to the __value__ of the option list (__not__ the label). 😎
